name: create-release
on:
  push:
    tags:
      - "*.*.*"
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Prepare Folder For Packaging
        run: |
          mkdir -p "Assets/VRLabs/ModularShaderSystem"
          ls | grep -v "Assets" | xargs mv -t "Assets/VRLabs/ModularShaderSystem"
          echo -e "fileFormatVersion: 2\nguid: 652a1ba5b00554143bc9a76307dbc4e8\nfolderAsset: yes\nDefaultImporter:\n  externalObjects: {}\n  userData: \n  assetBundleName: \n  assetBundleVariant: " > "Assets/VRLabs.meta"
          echo -e "fileFormatVersion: 2\nguid: 433bedcd0ded4bcf993b0088e99f493c\nfolderAsset: yes\nDefaultImporter:\n  externalObjects: {}\n  userData: \n  assetBundleName: \n  assetBundleVariant: " > "Assets/VRLabs/ModularShaderSystem.meta"
          mkdir -p "Main"
          mkdir -p "Examples"
          cp -r "Assets" "Main"
          cp -r "Assets" "Examples"
          rm -r "Main/Assets/VRLabs/ModularShaderSystem/Examples"
          rm -r "Main/Assets/VRLabs/ModularShaderSystem/Examples.meta"
          find "Examples/Assets/VRLabs/ModularShaderSystem" -mindepth 1 ! -regex '^Examples/Assets/VRLabs/ModularShaderSystem/Examples.*' -delete
      - name: Create UnityPackage
        env:
          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
        uses: FrostBanditTeam/extract-unity-package-action@1
        with:
          outputPackagePath: 'Modular.Shader.System.${{ env.SOURCE_TAG }}.unitypackage'
          unityProjectPath: 'Main'

      - name: Create Examples UnityPackage
        env:
          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
        uses: FrostBanditTeam/extract-unity-package-action@1
        with:
          outputPackagePath: 'Modular.Shader.System.Examples.${{ env.SOURCE_TAG }}.unitypackage'
          unityProjectPath: 'Examples'

      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v2
        with:
          configuration: ".github/release-notes-configuration.json"
          outputFile: "releaseNotes.txt"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: "Modular Shader System ${{ env.SOURCE_TAG }}"
          body_path: "releaseNotes.txt"
          files: |
            Modular.Shader.System.${{ env.SOURCE_TAG }}.unitypackage
            Modular.Shader.System.Examples.${{ env.SOURCE_TAG }}.unitypackage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}